openapi: 3.0.3
info:
  title: Order Service API
  version: 1.0.0
  description: API для управления заказами космических кораблей

servers:
  - url: http://localhost:8080
    description: Development server

x-ogen:
  target: shared/pkg/openapi/order/v1
  package: orderv1

paths:
  /api/v1/orders:
    $ref: './paths/orders.yaml'
  
  /api/v1/orders/{order_uuid}:
    $ref: './paths/order_by_uuid.yaml'
  
  /api/v1/orders/{order_uuid}/pay:
    $ref: './paths/order_pay.yaml'
  
  /api/v1/orders/{order_uuid}/cancel:
    $ref: './paths/order_cancel.yaml'

components:
  schemas:
    # Основные схемы
    CreateOrderRequest:
      $ref: './components/create_order_request.yaml'
    
    CreateOrderResponse:
      $ref: './components/create_order_response.yaml'
    
    PayOrderRequest:
      $ref: './components/pay_order_request.yaml'
    
    PayOrderResponse:
      $ref: './components/pay_order_response.yaml'
    
    Order:
      $ref: './components/order_dto.yaml'
    
    GetOrderResponse:
      $ref: './components/get_order_response.yaml'
    
    # Enums
    OrderStatus:
      $ref: './components/enums/order_status.yaml'
    
    PaymentMethod:
      $ref: './components/enums/payment_method.yaml'
    
    # Ошибки
    Error:
      $ref: './components/errors/generic_error.yaml'
    
    BadRequestError:
      $ref: './components/errors/bad_request_error.yaml'
    
    NotFoundError:
      $ref: './components/errors/not_found_error.yaml'
    
    ConflictError:
      $ref: './components/errors/conflict_error.yaml'
    
    InternalServerError:
      $ref: './components/errors/internal_server_error.yaml'
  
  parameters:
    OrderUuid:
      $ref: './params/order_uuid.yaml'

tags:
  - name: Orders
    description: Операции с заказами космических кораблей
